import re

def update_service():
    with open('service.html', 'r', encoding='utf-8') as f:
        content = f.read()

    replacements = [
        # Hero section
        ('Service</h1>', 'Technology</h1>'),
        ('Delivering tailored digital solutions that combine thoughtful strategy, intuitive design.', 
         'Explore the core protocols, custom hardware bridges, and security abstractions that power Locbit.'),
        
        # Section headings
        ('We provide the right solutions', 'Our Core Technologies'),
        ('Our design services', 'System Architecture'),
        ('How we charge', 'Resource Utilization'),
        ('You ask. We answer', 'Developer FAQ'),
        ('Trusted by teams', 'Built by Engineers'),

        # Services -> Technologies blocks
        ('Branding Design</div>', 'Go Modules</div>'),
        ('We build brand identities that feel intentional, distinctive, and built to last.', 
         'The entirely portable Go-based messaging logic handling identities and encryption states.'),
        
        ('UI/UX Design</div>', 'JNI / Gomobile Bridge</div>'),
        ('Every brand has a story \u2014 our role is to translate it into clear identities, thoughtful interfaces, and digital experiences.', 
         'A highly optimized C/C++ bridge generated by Gomobile allowing the Go engine to directly invoke native Android BLE APIs.'),
        
        ('Digital Experience</div>', 'BLE Mesh Routing</div>'),
        ('We refine, document, and hand off work ready to scale.', 
         'Offline packet broadcasting over adaptive Bluetooth channels without relying on centralized mesh servers.'),

        # Pricing -> Resource utilization
        ('Our Simple pricing', 'Resource Utilization'),
        ('STARTER PACKAGE', 'Background Service'),
        ('Ideal for startups and early-stage teams looking to establish a strong visual presence.', 
         'Minimal battery drain during background scanning and advertising modes.'),
        ('PROFESSIONAL PACKAGE', 'Active Transmission'),
        ('Perfect for businesses ready to scale with a polished brand and user-focused digital experience.', 
         'Higher burst power utilization while negotiating ECDH keys or transferring files.'),
        ('PRODUCT PACKAGE', 'Encryption Overhead'),
        ('Designed for teams building digital products that require clarity, usability, and scalability.', 
         'Negligible CPU cost natively leveraging AES-GCM instructions on modern ARM architecture.'),
         
        # Title
        ('Locbit - Webflow HTML Website Template', 'Locbit Technology \u2014 Deep Dive'),
    ]

    count = 0
    for old, new in replacements:
        if old in content:
            content = content.replace(old, new)
            count += 1
        else:
            pass

    with open('service.html', 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"Applied {count}/{len(replacements)} service.html replacements.")

if __name__ == '__main__':
    update_service()
